"use client";
import { compareOutput } from "@/lib/compare-output";
import { useState, useRef, useEffect } from "react";
import { languageConfigs } from "@/lib/languages";
import { canExecute } from "@/lib/execution-languages";
import { useWorkspace } from "./workspace-context";
import { Button } from "@/components/ui/button";
type Test = {id:string;input:string;expected:string;verify:boolean};
type RunResult = {output:string;error:string;elapsed:number;status:string};
const initial:Test={id:'first',input:'',expected:'',verify:false};
const normalize=(value:string)=>value.replace(/\r\n/g,'\n').replace(/\n$/,'');
export function BrowserRunner({code,language,title="Coding practice",context="",seededTests,problemId}:{code:string;language:string;title?:string;context?:string;seededTests?:{input:string;expected:string}[];problemId?:string}) {
 const w=useWorkspace(); const [autoNotes,setAutoNotes]=useState(true);
 const recorded=useRef(new Set<string>());const runLock=useRef(false);
 const [tests,setTests]=useState<Test[]>(seededTests?.map((t,i)=>({...t,id:'sample-'+i,verify:true}))||[initial]),[results,setResults]=useState<Record<string,RunResult>>({}),[running,setRunning]=useState(false),[snapshot,setSnapshot]=useState('');
 const cancel=useRef<()=>void>(()=>{}),abort=useRef(false),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;abort.current=true;cancel.current();};},[]);
 function execute(input:string):Promise<{output:string;error:string;elapsed:number}>{return new Promise(resolve=>{
   const frame=document.createElement('iframe');frame.hidden=true;frame.sandbox.add('allow-scripts');
   const token=crypto.randomUUID(),start=performance.now();let finished=false;let timer:ReturnType<typeof setTimeout>;
   function finish(output:string,error:string){if(finished)return;finished=true;clearTimeout(timer);window.removeEventListener('message',receive);frame.remove();resolve({output,error,elapsed:Math.round(performance.now()-start)});}
   function receive(e:MessageEvent){if(e.source!==frame.contentWindow||e.data?.token!==token)return;finish(String(e.data.output||'').slice(0,16000),String(e.data.error||'').slice(0,2000));}
   const worker=`const lines=[];let size=0;const print=(...args)=>{const s=args.map(v=>typeof v==='string'?v:JSON.stringify(v)??String(v)).join(' ');size+=s.length+1;if(size>16000)throw new Error('Output limit exceeded (16 KB)');lines.push(s);};console.log=print;console.error=print;console.warn=print;onmessage=async(e)=>{try{await new Function('stdin','print',e.data.code)(e.data.stdin,print);postMessage({output:lines.join('\\n'),error:''});}catch(err){postMessage({output:lines.join('\\n'),error:err.name+': '+err.message});}};`;
   const safe=(value:unknown)=>JSON.stringify(value).replace(/</g,'\\u003c');
   frame.srcdoc=`<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline' 'unsafe-eval' blob:; worker-src blob:; connect-src 'none';"><script>const w=new Worker(URL.createObjectURL(new Blob([${safe(worker)}],{type:'text/javascript'})));w.onmessage=e=>{parent.postMessage({token:${safe(token)},...e.data},'*');w.terminate();};w.onerror=()=>parent.postMessage({token:${safe(token)},error:'Runner failed to initialize.'},'*');w.postMessage(${safe({code,stdin:input})});</script>`;
   window.addEventListener('message',receive);timer=setTimeout(()=>finish('','Time limit exceeded (3 seconds).'),3000);cancel.current=()=>finish('','Cancelled');document.body.appendChild(frame);
 });}
 async function executeRemote(input:string){const controller=new AbortController();cancel.current=()=>controller.abort();const start=performance.now();try{const response=await fetch('/api/execute',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({language,code,input}),signal:controller.signal});const d=await response.json() as {output:string;error:string;elapsed:number};return response.ok?d:{output:'',error:d.error||'Compiler unavailable',elapsed:Math.round(performance.now()-start)};}catch{return {output:'',error:controller.signal.aborted?'Cancelled':'Could not reach compiler',elapsed:Math.round(performance.now()-start)};}}
 async function run(){if(runLock.current||running||!canExecute(language))return;runLock.current=true;setRunning(true);abort.current=false;setResults({});setSnapshot(JSON.stringify({code,language,tests}));
 try{for(const test of tests){if(abort.current)break;const result=await (language==='JavaScript'?execute(test.input):executeRemote(test.input));if(!mounted.current)break;if(abort.current)break;const status=result.error?'Error':!test.verify?'Executed':compareOutput(result.output,test.expected,test.input,problemId)?'Passed':'Wrong answer';setResults(old=>({...old,[test.id]:{...result,status}}));
 if(autoNotes && status!=='Executed' && result.error!=='Cancelled') {
  const category=status==='Wrong answer'?'Output mismatch':status==='Passed'?'Test passed after practice':/compil|error:|main\(/i.test(result.error)?'Compiler/runtime error':'Execution issue';
  const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify({title,code,input:test.input,expected:test.expected,status,error:result.error}))))).map(x=>x.toString(16).padStart(2,'0')).join('');
  const hadMistake=w.entries.some(e=>e.kind==='note'&&e.data.source==='Automatic mistake notebook'&&e.data.question===title);
  if((status!=='Passed'||hadMistake)&&!recorded.current.has(digest)&&!w.entries.some(e=>e.data.fingerprint===digest)) {
   recorded.current.add(digest);
   try{await w.save('note',title.slice(0,110)+' · '+category,{source:'Automatic mistake notebook',question:title,topic:category,language,fingerprint:digest,status,text:['## '+title,'**Observed result:** '+status,'**Language:** '+language,'### Problem',context.slice(0,3000),'### Input',test.input,'### Expected output',test.verify?test.expected:'Not supplied','### Actual output',result.output,'### Error',result.error||'None','### Code snapshot','~~~'+(languageConfigs.find(item=>item.name===language)?.extension||'text'),code.slice(0,16000),'~~~','### Reflection',status==='Passed'?'This test passed. Other inputs can still fail.':'Compare the first differing value, check boundaries and dry-run this input. The cause has not been confirmed automatically.'].join('\n\n')});}catch{recorded.current.delete(digest);w.setNotice('Test finished, but the automatic note could not be saved.');}
  }
 }}}finally{runLock.current=false;if(mounted.current)setRunning(false);}}
 useEffect(()=>{const handler=()=>{if(!running&&canExecute(language)&&code.trim())void run();};window.addEventListener('codementor-run-tests',handler);return()=>window.removeEventListener('codementor-run-tests',handler);});
 const stale=!!snapshot&&snapshot!==JSON.stringify({code,language,tests});
 function update(id:string,patch:Partial<Test>){setTests(old=>old.map(t=>t.id===id?{...t,...patch}:t));}
 return <section className="surface spaced"><div className="section-head"><h3>Test console</h3><span className="tag">{language}</span></div>
 <p className="runner-contract">{seededTests?.length?'Samples use a JSON array of function arguments. Read stdin, call your solution and print the result as JSON.':'Enter standard input below. Your program must print its output.'}{language!=='JavaScript'&&seededTests?.length?' Changing language loads a general starter; implement this question and its input parser before running.':''}</p>
 <div className="test-summary" role="status"><span>{running?'Running…':Object.keys(results).length?'Latest run':'Ready to test'}</span><strong>{Object.values(results).filter(r=>r.status==='Passed').length} passed</strong><span>{Object.values(results).filter(r=>r.status==='Wrong answer'||r.status==='Error').length} failed</span><span>{tests.length} cases</span></div>
 <label className="skill-option"><input type="checkbox" checked={autoNotes} onChange={e=>setAutoNotes(e.target.checked)}/>Save test mistakes to my notes automatically</label><details className="runner-help"><summary>Runtime & input help</summary><p>Run your code against custom inputs and compare actual output with expected output. JavaScript runs locally. Other programming languages send code and input to Judge0 (C++ and Julia use Compiler Explorer) for isolated execution. Internet is required; public services may be busy. Up to 100 remote test runs per day.</p>
 {language==='C++'&&<p>Use a complete C++ program with main(), cin for input and cout for output. Compile errors appear below. Up to 100 remote test runs per day; displayed time includes network and compilation. Stop cancels waiting and remaining tests; remote execution may finish independently.</p>}
 <details><summary>JavaScript input instructions</summary><p>Input is provided as the string <code>stdin</code>. Use <code>console.log</code> or <code>print</code>. A function definition alone produces no output: call your function.</p><pre>{'const [a, b] = stdin.trim().split(/\\s+/).map(Number);\nconsole.log(a + b);\n// Input: 2 3 → Output: 5'}</pre><p>Each test runs separately with a 3-second limit and a 16 KB output limit. Comparison normalizes Windows newlines and ignores one final newline; other spaces matter. Runtime includes worker startup, not a benchmark.</p></details>
 </details>
 {tests.map((test,i)=><fieldset key={test.id} className="surface spaced" disabled={running}><legend>Test case {i+1}</legend><div className="two-col"><label className="field">Input<textarea aria-label={`Input for test ${i+1}`} rows={3} maxLength={10000} value={test.input} onChange={e=>update(test.id,{input:e.target.value})}/></label><label className="field">Expected output<textarea aria-label={`Expected output for test ${i+1}`} rows={3} maxLength={16000} value={test.expected} onChange={e=>update(test.id,{expected:e.target.value,verify:true})}/></label></div><label className="skill-option"><input type="checkbox" checked={test.verify} onChange={e=>update(test.id,{verify:e.target.checked})}/>Compare expected output (including empty output)</label>
 {tests.length>1&&<Button type="button" variant="ghost" onClick={()=>setTests(old=>old.filter(t=>t.id!==test.id))}>Remove test {i+1}</Button>}
 {results[test.id]&&<div role="status" className={'test-result '+(results[test.id].status==='Passed'?'test-passed':results[test.id].error||results[test.id].status==='Wrong answer'?'test-failed':'')}><strong>{results[test.id].status} · {results[test.id].elapsed} ms</strong><p>Actual output</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{results[test.id].output||'(empty output)'}</pre>{results[test.id].error&&<p className="error">{results[test.id].error}</p>}</div>}</fieldset>)}
 <div className="actions">{seededTests?.length&&<Button type="button" variant="outline" disabled={running} onClick={()=>{setTests(seededTests.map((t,i)=>({...t,id:'sample-'+i,verify:true})));setResults({});setSnapshot('');}}>Restore sample tests</Button>}<Button type="button" variant="outline" disabled={running||tests.length>=10} onClick={()=>setTests(old=>[...old,{...initial,id:crypto.randomUUID()}])}>Add test case</Button><Button type="button" disabled={running||!canExecute(language)||!code.trim()} onClick={()=>void run()}>{running?'Running tests…':'Run all tests'}</Button>{running&&<Button type="button" variant="outline" onClick={()=>{abort.current=true;cancel.current();}}>Stop</Button>}</div>
 {!canExecute(language)&&<p>{language} requires a runtime that is not connected yet. Your code can still be saved and edited.</p>}
 {stale&&<p role="status">Code or test cases changed. Run again for current results.</p>}
 <small>Custom tests validate only the cases you provide; passing them does not prove correctness or acceptance on an external judge.</small>
 </section>;
}
