"use client";
import {useEffect,useState} from 'react';
type Bank={updated:string;topics:{name:string;slug:string;count:number}[];problems:{title:string;slug:string;difficulty:string;topics:string[];url:string}[]};
export function LeetcodeTopicBank(){
 const [bank,setBank]=useState<Bank|null>(null),[error,setError]=useState(''),[topic,setTopic]=useState('two-pointers'),[search,setSearch]=useState(''),[shown,setShown]=useState<Record<string,number>>({});
 useEffect(()=>{const controller=new AbortController();fetch('/leetcode-bank.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Could not load the library. Refresh to retry.');return r.json();}).then(b=>setBank(b as Bank)).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[]);
 if(error)return <p role="alert">{error}</p>;if(!bank)return <p role="status">Loading LeetCode topics…</p>;
 const selected=bank.topics.find(t=>t.slug===topic)||bank.topics[0];
 const problems=bank.problems.filter(p=>p.topics.includes(selected.slug)&&p.title.toLowerCase().includes(search.toLowerCase()));
 return <section><h2>Practice by topic</h2><p>{bank.problems.length.toLocaleString()} free LeetCode questions · official topic tags · Easy → Medium → Hard.</p><label className="field">LeetCode topic<select value={selected.slug} onChange={e=>{setTopic(e.target.value);setSearch('');setShown({});}}>{bank.topics.map(t=><option key={t.slug} value={t.slug}>{t.name} ({t.count})</option>)}</select></label><label className="field">Search this topic<input value={search} onChange={e=>{setSearch(e.target.value);setShown({});}} placeholder="Search question title"/></label>
 <p><strong>{selected.count} free questions in {selected.name}.</strong> {selected.count<100?'LeetCode currently provides fewer than 100 free questions with this exact tag.':'All available questions are included, not capped at 100.'}</p><p className="bank-source-note">These questions open on LeetCode for the full statement and official judge. The topic list is available here; full statements are not imported.</p>
 {['Easy','Medium','Hard'].map((level,i)=>{const rows=problems.filter(p=>p.difficulty===level),limit=shown[level]||20;return <section className="topic-stage" key={level}><h3>{i+1}. {level} · {rows.length}</h3><div className="problem-catalog">{rows.slice(0,limit).map(p=><a className="problem-catalog-row" key={p.slug} href={p.url} target="_blank" rel="noopener noreferrer"><span>{p.title} ↗</span><small>LeetCode · {level}</small></a>)}{!rows.length&&<p>No matching free questions at this level.</p>}</div>{rows.length>limit&&<button type="button" onClick={()=>setShown(old=>({...old,[level]:limit+20}))}>Show next {Math.min(20,rows.length-limit)} · {limit} of {rows.length} shown</button>}</section>;})}
 <small>Difficulty labels are from LeetCode. Questions within a level are not given an invented ranking. Snapshot: {new Date(bank.updated).toLocaleDateString()}.</small></section>;
}
