"use client";
import {useState,useEffect} from 'react';
export function PasswordForm({signup}:{signup:boolean}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[show,setShow]=useState(false);
 const [message,setMessage]=useState('');
 const [googleError,setGoogleError]=useState('');
 const [emailOpen,setEmailOpen]=useState(false),[capsLock,setCapsLock]=useState(false);
 useEffect(()=>{const reason=new URLSearchParams(window.location.search).get('google');if(reason==='existing')setEmailOpen(true);setGoogleError(reason==='setup'?'Google sign-in needs administrator setup.':reason==='existing'?'This email already has an account. Sign in below once with your existing password, then select the same Google account to link it. Future logins can use Google.':reason==='session'?'This Google sign-in attempt expired or was cancelled. Start again from this page.':reason==='credentials'?'Google rejected the app credentials. The administrator must check the Client ID and Secret.':reason==='exchange'?'Google could not complete the sign-in exchange. Start again from this page.':reason==='failed'?'Google sign-in could not finish. Please try again.':'');},[]);
 return <><a className="auth-continue" href="/api/google/start">{signup?"Create account with Google":"Sign in with Google"}</a>{googleError&&<p role="alert" className="error">{googleError}</p>}<div className="auth-method-divider"><span>or</span></div><button type="button" className="auth-email-choice" aria-expanded={emailOpen} aria-controls="email-auth-fields" onClick={()=>setEmailOpen(v=>!v)}>{signup?"Create account with email":"Sign in with email & password"}</button><div id="email-auth-fields" hidden={!emailOpen}><form className="password-form" onSubmit={async e=>{e.preventDefault();if(busy)return;const data=new FormData(e.currentTarget);const password=String(data.get('password')||'');if(signup&&password!==data.get('confirm')){setError('Passwords do not match.');return;}if(new TextEncoder().encode(password).length>72){setError('Password must fit within 72 UTF-8 bytes.');return;}setBusy(true);setError('');try{const r=await fetch('/api/auth/'+(signup?'signup':'login'),{method:'POST',signal:AbortSignal.timeout(20000),headers:{'Content-Type':'application/json'},body:JSON.stringify({email:data.get('email'),password,linkGoogle:!signup&&new URLSearchParams(window.location.search).get('google')==='existing',...(signup?{name:data.get('name')}:{})})});const result=await r.json() as {error?:string;googleRedirect?:string;verificationRequired?:boolean;message?:string};if(!r.ok)throw Error(result.error||'Unable to sign in.');if(result.googleRedirect){const target=new URL(result.googleRedirect);if(target.origin!=='https://accounts.google.com')throw Error('Invalid Google redirect.');window.location.assign(target.href);return;}if(result.verificationRequired){setMessage(result.message||'Check your email to verify your account.');setBusy(false);return;}try{sessionStorage.removeItem('codementor-problem-drafts');sessionStorage.removeItem('codementor-code-draft');sessionStorage.removeItem('codementor-selected-problem');}catch{}window.location.assign(new URLSearchParams(window.location.search).get('google')==='existing'?'/api/google/start':'/');}catch(e){setError(e instanceof Error?e.message:'Connection failed. Please retry.');setBusy(false);}}}>
 {signup&&<label className="field">Your name<input name="name" autoComplete="name" minLength={2} maxLength={80} required disabled={busy}/></label>}
 <label className="field">Email (your login ID)<input name="email" type="email" autoComplete="username" maxLength={254} required disabled={busy}/></label>
 <label className="field">Password<input onKeyUp={e=>setCapsLock(e.getModifierState('CapsLock'))} onBlur={()=>setCapsLock(false)} name="password" type={show?'text':'password'} autoComplete={signup?'new-password':'current-password'} minLength={12} maxLength={72} required disabled={busy}/></label>
 {signup&&<><small>Use 12–72 characters. A long, unique passphrase works well.</small><label className="field">Confirm password<input name="confirm" type={show?'text':'password'} autoComplete="new-password" minLength={12} maxLength={72} required disabled={busy}/></label></>}
 {capsLock&&<p role="status" className="auth-caps-warning">Caps Lock is on.</p>}
 <label className="password-show"><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/> Show password</label>
 {message&&<p role="status">{message}</p>}{error&&<p role="alert" className="error">{error}</p>}
 <button type="submit" className="auth-continue" disabled={busy}>{busy?'Please wait…':signup?'Create my account':'Sign in'}</button>
 {!signup&&<a href="/forgot-password">Forgot password?</a>}
 </form></div></>;
}
