"use client";
import {useEffect,useState} from 'react';
export function RecoveryForm({reset=false}:{reset?:boolean}){
 const [token,setToken]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[show,setShow]=useState(false);
 useEffect(()=>{if(reset){setToken(new URLSearchParams(location.hash.slice(1)).get('token')||'');history.replaceState(null,'',location.pathname);}setReady(true);},[reset]);
 return <main className="recovery-page"><section className="surface"><a href="/login">← Back to sign in</a><h1>{reset?'Create a new password':'Forgot password?'}</h1><p>{reset?'Choose a unique password. All existing sessions will be signed out.':'Enter your account email to request a secure reset link.'}</p>
 {reset&&ready&&!token&&!message?<p role="alert">Reset link missing. <a href="/forgot-password">Request a new link</a>.</p>:message?<div role="status"><p>{message}</p><a href="/login">Return to sign in</a></div>:<form className="password-form" onSubmit={async e=>{e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget),password=String(f.get('password')||'');if(reset&&password!==f.get('confirm')){setError('Passwords do not match.');return;}if(reset&&new TextEncoder().encode(password).length>72){setError('Password must fit within 72 UTF-8 bytes.');return;}setBusy(true);setError('');try{const r=await fetch('/api/auth/'+(reset?'reset-password':'forgot-password'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(reset?{token,password}:{email:f.get('email')})});const d=await r.json() as {message:string;error?:string};if(!r.ok)throw Error(d.error||'Please retry.');setMessage(d.message);if(reset){setToken('');try{sessionStorage.removeItem('codementor-code-draft');}catch{}}}catch(e){setError(e instanceof Error?e.message:'Could not connect.');}finally{setBusy(false);}}}>
 {reset?<><label className="field">New password<input name="password" type={show?'text':'password'} autoComplete="new-password" required minLength={12} maxLength={72} disabled={busy}/></label><label className="field">Confirm new password<input name="confirm" type={show?'text':'password'} autoComplete="new-password" required minLength={12} maxLength={72} disabled={busy}/></label><label className="password-show"><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/>Show password</label><small>Use at least 12 characters.</small></>:<label className="field">Account email<input name="email" type="email" autoComplete="email" required maxLength={254} disabled={busy}/></label>}
 {error&&<p role="alert" className="error">{error}</p>}<button className="auth-continue" type="submit" disabled={busy||!ready}>{busy?'Please wait…':reset?'Update password':'Send reset link'}</button></form>}</section></main>;
}
