"use client";
import {useState} from 'react';
import {Flame,Trophy,ChevronLeft,ChevronRight,ArrowUpRight,Check} from 'lucide-react';
import {dayKey,shiftDay,statistics} from '@/lib/learning';
import {useWorkspace} from './workspace-context';
export function StreakPanel({navigate}:{navigate:(page:string)=>void}){
 const w=useWorkspace(),s=statistics(w.entries,w.profile),[offset,setOffset]=useState(0),[selected,setSelected]=useState('');
 const questionsByDay=new Map<string,Set<string>>();for(const e of w.entries.filter(e=>e.kind==='attempt'&&e.data.problemId&&e.data.source!=='quiz')){const day=dayKey(e.created,w.profile.timezone),ids=questionsByDay.get(day)||new Set<string>();ids.add(e.data.problemId);questionsByDay.set(day,ids);}
 const counts=new Map(Array.from(questionsByDay,([day,ids])=>[day,ids.size]));
 const intensity=(count:number)=>count===0?0:count<=2?1:count<=5?2:count<=9?3:4;
 const month=new Date(s.today.slice(0,7)+'-01T12:00:00Z');month.setUTCMonth(month.getUTCMonth()+offset);
 const first=month.toISOString().slice(0,10),days=new Date(Date.UTC(month.getUTCFullYear(),month.getUTCMonth()+1,0)).getUTCDate(),pad=(month.getUTCDay()+6)%7;
 const activeToday=s.dates.includes(s.today),goal=Math.max(1,w.profile.dailyGoal),progress=Math.min(100,Math.round(s.todaySolved/goal*100));
 const week=Array.from({length:7},(_,i)=>shiftDay(s.today,i-6));
 const monthActive=Array.from(counts.keys()).filter(d=>d.startsWith(first.slice(0,7))).length;
 return <section className="streak-dashboard" aria-label="Your practice activity">
 <div className="streak-hero"><span className="streak-kicker">BUILD YOUR CONSISTENCY</span><div className="streak-total"><span className="streak-flame"><Flame size={38}/></span><strong>{s.streak}<small>day streak</small></strong></div><h2>{activeToday?'You showed up today.':s.streak?'Keep your streak alive.':'Your next chapter starts today.'}</h2><p>{activeToday?'Every attempt adds to your progress. Keep going at your pace.':'Log a practice attempt today to build your streak.'}</p><div className="streak-week">{week.map(day=><div key={day} title={day}><span>{new Date(day+'T12:00:00Z').toLocaleDateString('en',{weekday:'narrow',timeZone:'UTC'})}</span><i className={s.dates.includes(day)?'done':''}>{counts.has(day)?<Check size={15}/>:day===s.today?'·':''}</i></div>)}</div><button className="streak-cta" onClick={()=>navigate('Practice & quizzes')}>{activeToday?'Keep practising':'Start today’s practice'}<ArrowUpRight size={17}/></button><div className="streak-best"><Trophy size={16}/><strong>{s.longest} days</strong> max streak</div></div>
 <div className="streak-calendar"><div className="streak-calendar-heading"><div><span className="streak-kicker">ACTIVITY CALENDAR</span><h3>{month.toLocaleDateString('en',{month:'long',year:'numeric',timeZone:'UTC'})}</h3></div><div className="streak-month-controls"><button aria-label="Previous month" onClick={()=>{setOffset(offset-1);setSelected('');}}><ChevronLeft size={17}/></button><button aria-label="Next month" disabled={offset===0} onClick={()=>{setOffset(offset+1);setSelected('');}}><ChevronRight size={17}/></button></div></div><div className="streak-month-stats"><strong>{monthActive}</strong> active days this month <span>•</span> {w.profile.timezone}</div><div className="streak-calendar-grid">{['M','T','W','T','F','S','S'].map((d,i)=><span className="calendar-weekday" key={i}>{d}</span>)}{Array.from({length:pad},(_,i)=><span key={'pad'+i}/>)}{Array.from({length:days},(_,i)=>{const day=shiftDay(first,i),count=counts.get(day)||0;return <button key={day} disabled={day>s.today} className={'calendar-day intensity-'+intensity(count)+(day===s.today?' is-today':'')+(selected===day?' is-selected':'')} aria-label={day+': '+count+' unique questions practised'} aria-pressed={selected===day} title={day+': '+count+' unique questions practised'} onClick={()=>setSelected(day)}>{i+1}</button>;})}</div><div className="streak-calendar-detail" aria-live="polite">{selected?selected+' · '+(counts.get(selected)||0)+' unique questions practised':'Select a date to see your activity.'}</div><div className="streak-legend">Less{[0,1,2,3,4].map(n=><i key={n} className={'intensity-'+n}/>)}More <span>0 · 1–2 · 3–5 · 6–9 · 10+ unique questions</span></div></div>
 <div className="streak-goal"><div><span className="streak-kicker">TODAY’S SOLVING GOAL</span><strong>{s.todaySolved}<small> / {goal} problems</small></strong></div><div className="streak-goal-track" role="progressbar" aria-label="Daily solving goal" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress}><span style={{width:progress+'%'}}/></div><span>{progress===100?'Goal complete — great work!':goal-s.todaySolved+' more to reach your goal'}</span><button onClick={()=>navigate('Settings')}>Edit goal</button></div>
 </section>;
}
