export const branches = [
  "Computer Science / IT",
  "Electronics / Communication",
  "Electrical",
  "Mechanical",
  "Civil",
  "Chemical",
  "Aerospace",
  "Biomedical / Biotechnology",
  "Production / Industrial",
  "Materials / Metallurgy",
  "Instrumentation",
  "Mechatronics / Robotics",
  "Automobile",
  "Environmental",
  "Agricultural / Food",
  "Mining",
  "Petroleum",
  "Marine / Naval",
  "Textile",
  "Other",
];
