export const stages = [
  {
    id: "start",
    title: "Start from zero",
    subtitle: "Input, variables and decisions",
    level: "Foundation",
    items: [
      "Choose one language and run Hello World",
      "Read input and print formatted output",
      "Use variables, types and arithmetic",
      "Write if / else and switch decisions",
      "Use for and while loops",
      "Trace a program by hand",
    ],
    exercise:
      "Read two numbers and print their sum, minimum and maximum. Try equal and negative inputs.",
    check: "Can you explain every line without looking at notes?",
    url: "https://www.codechef.com/practice/basic-programming-concepts",
  },
  {
    id: "functions",
    title: "Build programming fluency",
    subtitle: "Functions, arrays and strings",
    level: "Beginner",
    items: [
      "Write reusable functions",
      "Understand parameters and return values",
      "Traverse arrays and strings",
      "Count frequencies",
      "Compare recursion and iteration",
      "Debug boundary cases",
    ],
    exercise:
      "Count the frequency of each character in a string. Explain what changes when case matters.",
    check: "Can you solve small problems without copying syntax?",
    url: "https://www.codechef.com/practice",
  },
  {
    id: "stl",
    title: "Make the standard library work for you",
    subtitle: "Containers, iterators and algorithms",
    level: "Beginner",
    items: [
      "Use vector, pair and string",
      "Use stack, queue and deque",
      "Compare map, set and hash containers",
      "Use sort, lower_bound and upper_bound",
      "Use priority_queue and custom comparators",
      "Know operation costs and iterator pitfalls",
    ],
    exercise:
      "Read numbers and print the three most frequent values. Define how ties should be handled.",
    check: "Can you choose a container and justify its time and space cost?",
    url: "https://en.cppreference.com/w/cpp/container.html",
  },
  {
    id: "patterns",
    title: "Learn core problem-solving patterns",
    subtitle: "Two pointers, search and recursion",
    level: "Intermediate",
    items: [
      "Two pointers and sliding windows",
      "Prefix sums and difference arrays",
      "Binary search and search on answer",
      "Recursion and backtracking",
      "Linked-list pointer operations",
      "Bit manipulation fundamentals",
    ],
    exercise:
      "Find the smallest window whose sum is at least a target for a positive-number array. Explain why negative values change the approach.",
    check: "Can you derive an invariant before writing code?",
    url: "https://takeuforward.org/dsa/strivers-a2z-sheet-learn-dsa-a-to-z",
  },
  {
    id: "structures",
    title: "Master trees and graphs",
    subtitle: "Explore relationships efficiently",
    level: "Intermediate",
    items: [
      "Tree DFS and level-order traversal",
      "BST operations and invariants",
      "Heap-based selection",
      "Graph BFS and DFS",
      "Topological sorting and cycle detection",
      "Shortest paths, DSU and spanning trees",
    ],
    exercise:
      "Model course prerequisites as a graph and detect whether all courses can be completed.",
    check: "Can you explain O(V+E), visited state and disconnected components?",
    url: "https://codeforces.com/problemset",
  },
  {
    id: "dp",
    title: "Reason about optimisation",
    subtitle: "Greedy proofs and dynamic programming",
    level: "Advanced",
    items: [
      "Greedy exchange arguments",
      "Memoization and tabulation",
      "Knapsack and subsequence patterns",
      "Grid and interval DP",
      "Space optimisation",
      "Tries and range-query structures",
    ],
    exercise:
      "Solve coin change. Define the state, transitions, base cases and unreachable states before coding.",
    check: "Can you justify correctness and derive the complexity from states?",
    url: "https://takeuforward.org/dsa/strivers-a2z-sheet-learn-dsa-a-to-z",
  },
  {
    id: "cp",
    title: "Compete with confidence",
    subtitle: "CodeChef → Codeforces progression",
    level: "Competitive",
    items: [
      "Start with untimed easy problems",
      "Try Codeforces 800–1000 practice",
      "Upsolve every missed contest problem",
      "Progress to 1100–1400 problems",
      "Study number theory and modular arithmetic",
      "Try virtual contests and maintain a mistake log",
    ],
    exercise:
      "Run a 60-minute practice session, then spend equal time upsolving and recording why each approach failed.",
    check:
      "Can you solve reliably under time pressure and learn from a wrong submission?",
    url: "https://codeforces.com/contests",
  },
  {
    id: "interview",
    title: "Turn knowledge into interview skill",
    subtitle: "Communicate, build and demonstrate",
    level: "Placement",
    items: [
      "Explain tradeoffs aloud",
      "Practice mock interviews",
      "Revise OOP, OS and DBMS",
      "Write tests and clean documentation",
      "Show working projects and honest metrics",
      "Review your resume and portfolio",
    ],
    exercise:
      "Explain one project in two minutes: the problem, your architecture, a hard tradeoff and evidence that it works.",
    check: "Can you defend your choices and show your own work?",
    url: "https://www.codechef.com/practice",
  },
];
export const stlReference = [
  [
    "vector",
    "vector<int> v; v.push_back(x); v[i];",
    "Index O(1); push_back amortized O(1); middle insert/erase O(n).",
    "reserve changes capacity, not size. Reallocation invalidates iterators.",
  ],
  [
    "pair & tuple",
    "pair<int,int> p={1,2}; auto [a,b]=p;",
    "Access O(1); comparison follows element order.",
    "Structured bindings need C++17.",
  ],
  [
    "string",
    'string s="abc"; s.substr(pos,len);',
    "Index O(1); substring O(length); middle edits often O(n).",
    "substr can throw when pos exceeds size.",
  ],
  [
    "stack",
    "stack<int> s; s.push(x); s.top(); s.pop();",
    "Push, pop and top O(1) with the default deque.",
    "Check empty() before top() or pop(). pop() returns void.",
  ],
  [
    "queue",
    "queue<int> q; q.push(x); q.front(); q.pop();",
    "Push, pop and front O(1) with default deque.",
    "FIFO. Do not use front() on an empty queue.",
  ],
  [
    "deque",
    "deque<int> d; d.push_front(x); d.push_back(y);",
    "End insertion/removal and indexing O(1); middle edits O(n).",
    "Storage is not contiguous.",
  ],
  [
    "priority_queue",
    "priority_queue<int> q; q.push(x); q.top();",
    "Top O(1); push/pop O(log n).",
    "Default is a max-heap; use greater<int> for a min-heap.",
  ],
  [
    "set / multiset",
    "set<int> s; s.insert(x); s.find(x);",
    "Insert, find and key erase O(log n).",
    "set keeps unique keys; multiset permits duplicates.",
  ],
  [
    "map",
    "map<string,int> m; ++m[key];",
    "Lookup, insertion and key erase O(log n).",
    "operator[] inserts missing keys.",
  ],
  [
    "unordered_map / unordered_set",
    "unordered_map<int,int> m; m.find(key);",
    "Average O(1); worst-case O(n) lookup, insertion, erasure.",
    "No sorted order; collisions matter.",
  ],
  [
    "sort / stable_sort",
    "sort(v.begin(),v.end());",
    "sort O(n log n) comparisons; stable_sort implementation memory affects bounds.",
    "Comparator must define strict weak ordering; use <, not <=.",
  ],
  [
    "lower_bound / upper_bound",
    "auto i=lower_bound(v.begin(),v.end(),x);",
    "O(log n) comparisons; non-random iterators may need O(n) movement.",
    "Range must be partitioned appropriately; ascending sorted input is the usual case.",
  ],
  [
    "binary_search",
    "bool found=binary_search(v.begin(),v.end(),x);",
    "O(log n) comparisons on a sorted range.",
    "Returns a bool, not an index.",
  ],
  [
    "accumulate / iota",
    "long long sum=accumulate(v.begin(),v.end(),0LL);",
    "O(n) operations.",
    "The initial value controls the accumulator type; avoid overflow.",
  ],
  [
    "min_element / max_element",
    "auto it=max_element(v.begin(),v.end());",
    "O(n) comparisons.",
    "For an empty range, returns end().",
  ],
  [
    "reverse / rotate",
    "reverse(v.begin(),v.end());",
    "O(n) element operations.",
    "reverse mutates the range.",
  ],
  [
    "unique / erase",
    "v.erase(unique(v.begin(),v.end()),v.end());",
    "O(n) comparisons and element movement.",
    "unique only groups adjacent duplicates; sort first when appropriate.",
  ],
  [
    "next_permutation",
    "while(next_permutation(v.begin(),v.end())) {}",
    "O(n) per step; enumerating permutations can take O(n·n!).",
    "Start sorted to enumerate all distinct permutations.",
  ],
  [
    "gcd / lcm",
    "auto g=gcd(a,b); // <numeric>",
    "Euclidean gcd O(log min(a,b)) arithmetic steps.",
    "lcm can overflow even when inputs fit.",
  ],
  [
    "Fast I/O",
    "ios::sync_with_stdio(false); cin.tie(nullptr);",
    "Reduces stream overhead; does not change algorithmic complexity.",
    "Avoid mixing C and C++ I/O after disabling synchronization.",
  ],
];
