import { twoPointerProgression } from './two-pointer-progression';
import { expandedProblems } from './practice-expansion';
export type GuidedProblem = {id:string;difficulty?:"Easy"|"Medium"|"Hard";tests?:{input:string;expected:string}[];title:string;topic:string;statement:string;constraints:string;examples:{input:string;output:string;why:string}[];hints:string[];steps:string[];code:string;cost:string;pitfalls:string;similar:string[]};
const originalProblems:GuidedProblem[] = [
{id:'pair',title:'Find a target pair',topic:'Hashing',statement:'Implement solve(nums, target). Return two distinct zero-based indices whose values add to target. Return [] if no pair exists. Any valid pair is accepted. Do not modify nums.',constraints:'0 ≤ nums.length ≤ 100,000; integer values and target between -1,000,000 and 1,000,000. Duplicate values are allowed.',examples:[{input:'[4, 9, 2, 7], 11',output:'[1, 2]',why:'9 + 2 = 11. [0, 3] is also valid.'},{input:'[5, 5], 10',output:'[0, 1]',why:'Equal values may be used if their indices differ.'},{input:'[2], 4',output:'[]',why:'The same index cannot be used twice.'}],hints:['Try every pair first. How many pairs are there?','For a value x, the missing partner is target - x.','Store earlier values and their indices. Check the partner before storing x.'],steps:['Read 4: need 7. Nothing stored yet, so remember 4 → 0.','Read 9: need 2. Remember 9 → 1.','Read 2: need 9. It is stored at index 1; return [1, 2].'],code:'function solve(nums, target) {\n  const seen = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const need = target - nums[i];\n    if (seen.has(need)) return [seen.get(need), i];\n    seen.set(nums[i], i);\n  }\n  return [];\n}\nconsole.log(solve([4, 9, 2, 7], 11));',cost:'Brute force: O(n²) time, O(1) auxiliary space. Hash-map approach: expected O(n) time under constant-average hash operations, O(n) auxiliary space.',pitfalls:'Do not insert before checking: that could reuse the current index. Map indices are zero-based. [] means no solution.',similar:['sorted-pair','frequency']},
{id:'sorted-pair',title:'Pair in a sorted array',topic:'Two pointers',statement:'Implement solve(nums, target). nums is sorted in nondecreasing order. Return two distinct zero-based indices adding to target, or [] if none exists. Any valid pair is accepted.',constraints:'0 ≤ n ≤ 100,000; integer values and target between -1,000,000 and 1,000,000. Input is already sorted.',examples:[{input:'[1, 3, 6, 8], 9',output:'[0, 3]',why:'1 + 8 = 9; [1, 2] also works.'},{input:'[1, 2, 4, 9], 6',output:'[1, 2]',why:'2 + 4 = 6.'},{input:'[], 5',output:'[]',why:'No elements means no pair.'}],hints:['Start with the smallest and largest values.','If the sum is too small, which end can increase it?','Move left forward for a small sum and right backward for a large sum.'],steps:['For [1,2,4,9], target 6: left=0, right=3, sum=10; decrease right.','left=0, right=2, sum=5; increase left.','left=1, right=2, sum=6; return [1,2].'],code:'function solve(nums, target) {\n  let left = 0, right = nums.length - 1;\n  while (left < right) {\n    const sum = nums[left] + nums[right];\n    if (sum === target) return [left, right];\n    if (sum < target) left++; else right--;\n  }\n  return [];\n}\nconsole.log(solve([1, 2, 4, 9], 6));',cost:'O(n) time, O(1) auxiliary space. Each move eliminates one index. A nested-pair scan costs O(n²).',pitfalls:'This elimination argument requires sorted input. Sorting an unsorted array changes its original indices.',similar:['pair','binary']},
{id:'binary',title:'Locate a value',topic:'Binary search',statement:'Implement solve(nums, target). Given strictly increasing integers, return the zero-based index of target, or -1 if absent. Do not modify the array.',constraints:'0 ≤ n ≤ 100,000; values and target are integers between -1,000,000 and 1,000,000. No duplicate values.',examples:[{input:'[2, 5, 8, 12, 20], 12',output:'3',why:'nums[3] is 12.'},{input:'[2, 5, 8], 6',output:'-1',why:'6 is absent.'},{input:'[], 2',output:'-1',why:'The search interval starts empty.'}],hints:['A linear scan works but ignores the sorted order.','Compare the middle value with target.','Keep the possible answer inside the inclusive interval [lo, hi].'],steps:['lo=0, hi=4, mid=2: value 8 is smaller than 12, so lo=3.','lo=3, hi=4, mid=3: value 12 matches; return 3.'],code:'function solve(nums, target) {\n  let lo = 0, hi = nums.length - 1;\n  while (lo <= hi) {\n    const mid = lo + Math.floor((hi - lo) / 2);\n    if (nums[mid] === target) return mid;\n    if (nums[mid] < target) lo = mid + 1;\n    else hi = mid - 1;\n  }\n  return -1;\n}\nconsole.log(solve([2, 5, 8, 12, 20], 12));',cost:'O(log n) time for nonempty input; O(1) auxiliary space. A linear scan is O(n).',pitfalls:'Use lo <= hi for an inclusive interval. Move past mid to guarantee progress. Do not apply this to arbitrary unsorted input.',similar:['sorted-pair','range']},
{id:'range',title:'Answer range sums',topic:'Prefix sums',statement:'Implement solve(nums, queries). Each query [l,r] asks for the sum from index l through r, inclusive. Return one sum per query in the original order. nums never changes between queries.',constraints:'1 ≤ n ≤ 100,000; 0 ≤ queries.length ≤ 100,000; -1,000,000 ≤ nums[i] ≤ 1,000,000; 0 ≤ l ≤ r < n. Sums fit exactly in JavaScript Number under these limits.',examples:[{input:'[3, -1, 4, 2], [[1,3],[0,0]]',output:'[5, 3]',why:'-1 + 4 + 2 = 5; the single value at index 0 is 3.'},{input:'[7], []',output:'[]',why:'No queries means no answers.'}],hints:['Summing every range independently can repeat work.','Store the sum of everything before each position.','With prefix[0]=0, sum(l..r)=prefix[r+1]-prefix[l].'],steps:['For [3,-1,4,2], build prefix=[0,3,2,6,8].','Query [1,3]: prefix[4]-prefix[1]=8-3=5.','Query [0,0]: prefix[1]-prefix[0]=3-0=3.'],code:'function solve(nums, queries) {\n  const prefix = [0];\n  for (const x of nums) prefix.push(prefix[prefix.length - 1] + x);\n  return queries.map(([l, r]) => prefix[r + 1] - prefix[l]);\n}\nconsole.log(solve([3, -1, 4, 2], [[1, 3], [0, 0]]));',cost:'O(n+q) time; O(n) auxiliary prefix storage plus O(q) returned output. Repeated scans can take O(nq).',pitfalls:'The query ends at r, but the prefix lookup is r+1. If nums changes, old prefix sums become stale.',similar:['binary','frequency']},
{id:'frequency',title:'Most frequent value',topic:'Hashing',statement:'Implement solve(nums). Return the most frequent integer. If several values tie, return the smallest. Return null for an empty array.',constraints:'0 ≤ n ≤ 100,000; integer values from -1,000,000 to 1,000,000. Do not mutate nums.',examples:[{input:'[6, 2, 6, 2, 8]',output:'2',why:'2 and 6 both appear twice; the smaller value wins.'},{input:'[-3, -3, 1]',output:'-3',why:'Negative values are valid keys.'},{input:'[]',output:'null',why:'There is no most frequent value.'}],hints:['Count how often each value appears.','Keep the largest count and the chosen value.','When counts tie, compare the values numerically.'],steps:['Counts for [6,2,6,2,8] are 6→2, 2→2, 8→1.','Choose 6 initially with count 2.','2 ties with count 2 and is smaller, so choose 2. 8 cannot replace it.'],code:'function solve(nums) {\n  const counts = new Map();\n  for (const x of nums) counts.set(x, (counts.get(x) || 0) + 1);\n  let answer = null, best = 0;\n  for (const [x, count] of counts) {\n    if (count > best || (count === best && (answer === null || x < answer))) {\n      answer = x; best = count;\n    }\n  }\n  return answer;\n}\nconsole.log(solve([6, 2, 6, 2, 8]));',cost:'Expected O(n) time with average constant-time hash operations; O(k) auxiliary space for k distinct values.',pitfalls:'Do not rely on insertion order to break ties. Check empty input explicitly through the null initial result.',similar:['pair','range']}
];
const legacyCases:Record<string,{args:unknown[];expected:unknown}[]>={
 pair:[{args:[[4,9,2,7],11],expected:[1,2]},{args:[[5,5],10],expected:[0,1]},{args:[[2],4],expected:[]}],
 'sorted-pair':[{args:[[1,3,6,8],9],expected:[0,3]},{args:[[1,2,4,9],6],expected:[1,2]},{args:[[],5],expected:[]}],
 binary:[{args:[[2,5,8,12,20],12],expected:3},{args:[[2,5,8],6],expected:-1},{args:[[],2],expected:-1}],
 range:[{args:[[3,-1,4,2],[[1,3],[0,0]]],expected:[5,3]},{args:[[7],[]],expected:[]}],
 frequency:[{args:[[6,2,6,2,8]],expected:2},{args:[[-3,-3,1]],expected:-3},{args:[[]],expected:null}]
};
export const guidedProblems:GuidedProblem[]=[...originalProblems.map(p=>({...p,difficulty:'Easy' as const,code:p.code.slice(0,p.code.lastIndexOf('console.log')).trim(),tests:legacyCases[p.id].map(c=>({input:JSON.stringify(c.args),expected:JSON.stringify(c.expected)})),examples:p.examples.map((e,i)=>({...e,input:JSON.stringify(legacyCases[p.id][i].args)}))})),...expandedProblems,...twoPointerProgression];
export function runnableCode(p:GuidedProblem,solution:boolean){
 const signature=p.code.match(/function solve\(([^)]*)\)/)?.[1]||'...args';
 const body=solution?p.code:'function solve('+signature+') {\n  // Implement your solution here.\n  throw new Error("Solution not implemented yet");\n}';
 return body+'\n\n// Input is a JSON array of function arguments.\nconst args = JSON.parse(stdin.trim() || '+JSON.stringify(p.tests?.[0]?.input||'[]')+');\nconsole.log(JSON.stringify(solve(...args)));\n';
}
export function problemText(p:GuidedProblem){return `${p.title}\n\n${p.statement}\n\nConstraints: ${p.constraints}\n\n${p.examples.map((e,i)=>`Example ${i+1}\nInput: ${e.input}\nOutput: ${e.output}\nExplanation: ${e.why}`).join('\n\n')}`;}
